### PR TITLE
add syslog logging option for atomic execution

### PR DESCRIPTION
**Pull request by clr2of8**
You can optionally add a syslog server and port to Public\config.ps1 and the default logger will send the atomic execution log to your syslog server as well as write it to disk. If you don't configure a syslog server, everything works the way it did before with just logging to a file.

### CODE REVIEW

**Review by MSAdministrator — COMMENTED** [review]
Not sure if it should be in this PR or not but I would make sure that there is documentation for this new `config.ps1` file.

Some questions:

1. Should we name the variables something that will guarantee not to conflict with other variables on the system? I think the ones used are fine but might be worth adding ART or something atomic-red-team related to the variable names but this is only a suggestion (Not blocking).
2. Do you think there's value in adding the syslog params as a parameter to Invoke-Atomic or not? I don't know how much this will be used so not sure if it should be a full fledged feature or not.

**Comment by clr2of8** [comment]
Those are good questions. The first item had crossed my mind and yes I think this would be good. I'll update it. I have some other additions planned that are going to need a config file so I think we don't need to add command line switch in this case. For the documentation of the config file, I'll add that to the wiki section [here](https://github.com/redcanaryco/invoke-atomicredteam/wiki/Execution-Logging) once the PR is approved.

**Comment by clr2of8** [comment]
I added the config to a custom PowerShell object with a name of `artConfig` where each setting can be references using dot notation like `$artConfig.syslogPort`

**Comment by clr2of8** [comment]
Moving to draft because I want to update to use proper syslog format first

**Comment by clr2of8** [comment]
Closing for now, will submit a fresh PR when ready.

**Pull request closed without merging**
